version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./src:/application
            #- ./logs/nginx:/var/log/nginx
        networks:
            - sellmo
        links:
            - php
    php:
        build: ./docker/images/php/
        links:
            - mysql
        volumes:
            - ./src:/application
        networks:
            - sellmo
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'sellmo'
            MYSQL_USER: 'sellmo'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        #volumes:
        networks:
            - sellmo
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        #volumes:
         #   - 'sail-redis:/data'
        networks:
            - sellmo
        healthcheck:
            retries: 3
            timeout: 5s
networks:
    sellmo:
        driver: bridge
volumes:
    sellmo-mysql:
        driver: local
    sellmo-redis:
        driver: local
